sudo: false
language: node_js
node_js:
  - "lts/*"
os:
  - osx

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm run lint
  - npm run test:coverage && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls